"""empty message

Revision ID: 0bed7dde38fc
Revises: 1abd332cb167
Create Date: 2018-12-03 18:08:05.439330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bed7dde38fc'
down_revision = '1abd332cb167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
