"""empty message

Revision ID: 1abd332cb167
Revises: d161ab62eae4
Create Date: 2018-12-03 18:02:46.925606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abd332cb167'
down_revision = 'd161ab62eae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('stars', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('stars', 'id_')
    # ### end Alembic commands ###
