"""empty message

Revision ID: b1f9df3d1d87
Revises: 37b7d50f4c88
Create Date: 2018-12-03 00:25:51.861447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f9df3d1d87'
down_revision = '37b7d50f4c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('parent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'parent')
    # ### end Alembic commands ###
