"""empty message

Revision ID: d161ab62eae4
Revises: b1f9df3d1d87
Create Date: 2018-12-03 17:56:10.098300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd161ab62eae4'
down_revision = 'b1f9df3d1d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_index('stars_project_id_uindex', table_name='stars')
    op.drop_index('stars_s_id_uindex', table_name='stars')
    op.drop_index('stars_user_id_uindex', table_name='stars')
    op.drop_column('stars', 's_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('s_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('stars_user_id_uindex', 'stars', ['user_id'], unique=True)
    op.create_index('stars_s_id_uindex', 'stars', ['s_id'], unique=True)
    op.create_index('stars_project_id_uindex', 'stars', ['project_id'], unique=True)
    op.drop_column('stars', 'id')
    # ### end Alembic commands ###
